shopping:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: 'ODBC Driver 18 for SQL Server' # (The ODBC Driver installed on your system)
      server: DESKTOP-P9IPHVA
      database: shopping
      schema: dbo
      windows_login: True
      trust_cert: True
      # user:
      # password:

    staging:
      type: sqlserver
      driver: 'ODBC Driver 18 for SQL Server' # (The ODBC Driver installed on your system)
      server: LAPTOP-RKFE274I
      database: demo
      schema: dbo
      windows_login: True
      trust_cert: True
      
    production:
      type: sqlserver
      driver: 'ODBC Driver 18 for SQL Server' # (The ODBC Driver installed on your system)
      server: LAPTOP-RKFE274I
      database: industry
      schema: dbo
      windows_login: True
      trust_cert: True